version: '3.8'

services:
  database:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=crm
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
